### ISSUE TITLE
crash on worker queue without project settings.

### ISSUE THREAD

**Issue by nikhilm** [iron-io/ironcli#100]
Pre urfave:
```
./ironcli worker queue -h                                                                                                                                                                                    afe7415
usage: iron worker queue [OPTIONS] CODE_PACKAGE_NAME
  -cluster string
        optional: specify cluster to queue task on
  -delay int
        seconds to delay before queueing task
  -encryption-key string
        optional: specify an rsa public encryption key
  -encryption-key-file string
        optional: specify the location of a file containing an rsa public encryption key
  -label string
        optional: specify label for a task
  -payload string
        give worker payload
  -payload-file string
        give worker payload of file contents
  -priority int
        0(default), 1 or 2; uses worker's default priority if unset (default -3)
  -timeout int
        0-3600(default) max runtime for task in seconds (default 3600)
  -wait
        wait for task to complete and print log
```

post urfave (master):

```
./ironcli worker queue -h                                                                                                                                                                                     master
2016/09/29 14:58:34 Didn't find token or project_id in configs. Check your environment or iron.json.
panic: Didn't find token or project_id in configs. Check your environment or iron.json.


goroutine 1 [running]:
panic(0x4bb8c0, 0xc82010a3c0)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
log.Panicln(0xc820114fe0, 0x1, 0x1)
        /usr/local/go/src/log/log.go:334 +0xc1
github.com/iron-io/ironcli/vendor/github.com/iron-io/iron_go3/config.config(0x689930, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/nikhil/iron/gocode/src/github.com/iron-io/ironcli/vendor/github.com/iron-io/iron_go3/config/config.go:121 +0x566
github.com/iron-io/ironcli/vendor/github.com/iron-io/iron_go3/config.ConfigWithEnv(0x689930, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/nikhil/iron/gocode/src/github.com/iron-io/ironcli/vendor/github.com/iron-io/iron_go3/config/config.go:88 +0x90
github.com/iron-io/ironcli/common.settingValues(0xc8200a3360)
        /Users/nikhil/iron/gocode/src/github.com/iron-io/ironcli/common/settings.go:20 +0x72
github.com/iron-io/ironcli/common.setProject(0xc8200a3360, 0x0, 0x0)
        /Users/nikhil/iron/gocode/src/github.com/iron-io/ironcli/common/settings.go:60 +0x42
github.com/iron-io/ironcli/common.SetSettings(0xc8200a3360, 0x0, 0x0)
        /Users/nikhil/iron/gocode/src/github.com/iron-io/ironcli/common/settings.go:80 +0x115
github.com/iron-io/ironcli/cmd/worker.NewWorker.func1(0xc8200a52c0, 0x0, 0x0)
        /Users/nikhil/iron/gocode/src/github.com/iron-io/ironcli/cmd/worker/worker.go:20 +0x3e
github.com/iron-io/ironcli/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc82008e780, 0xc8200a5180, 0x0, 0x0)
        /Users/nikhil/iron/gocode/src/github.com/iron-io/ironcli/vendor/github.com/urfave/cli/app.go:342 +0xe71
github.com/iron-io/ironcli/vendor/github.com/urfave/cli.Command.startApp(0x679d10, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x707d60, 0x25, 0x0, ...)
        /Users/nikhil/iron/gocode/src/github.com/iron-io/ironcli/vendor/github.com/urfave/cli/command.go:273 +0xa30
github.com/iron-io/ironcli/vendor/github.com/urfave/cli.Command.Run(0x679d10, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x707d60, 0x25, 0x0, ...)
        /Users/nikhil/iron/gocode/src/github.com/iron-io/ironcli/vendor/github.com/urfave/cli/command.go:74 +0x7b
github.com/iron-io/ironcli/vendor/github.com/urfave/cli.(*App).Run(0xc82008e300, 0xc820070080, 0x4, 0x4, 0x0, 0x0)
        /Users/nikhil/iron/gocode/src/github.com/iron-io/ironcli/vendor/github.com/urfave/cli/app.go:235 +0xa9c
main.main()
        /Users/nikhil/iron/gocode/src/github.com/iron-io/ironcli/main.go:81 +0x91f
```

Could you literally just run this with every command+subcommand with `-h` flag and make sure they don't crash. Make this a higher priority than the tests. Thank you.

**Comment by Nyarum** [comment]
Fixed.
